# Default values for was-liberty-hello-world
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
lastConfigLoaded: "2023-10-01_00-00-00"
appName: was-liberty-hello-world-helm
