kind: Service
apiVersion: v1
metadata:
  name: was-sample-app-helm
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: was-sample-app-helm
    chart.name: {{ .Chart.Name }}
    chart.version: {{ .Chart.Version }}
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
  type: ClusterIP
  selector:
    app.kubernetes.io/name: was-sample-app-helm
